stages:
  - build
  - test

build_job:
  stage: build
  script:
    - echo "Building the project..."
    - mvn clean
  only:
    - merge_requests

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - mvn test
  only:
    - merge_requests
