services:
  - type: web
    name: travel-agency
    env: java
    repo: https://github.com/dimonkoval/travel-agency
    region: frankfurt
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/travel.agency-0.0.1-SNAPSHOT.jar
    branch: main
#    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8090
      - key: DB_URL
        value: jdbc:h2:file:./data/traveldb;AUTO_SERVER=TRUE
