services:
  - type: web
    name: travel-agency
    region: frankfurt    # або інший регіон за потреби
    plan: free           # або оплачені плани
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "8080"
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
        value: "fake-google-id"
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
        value: "fake-google-secret"
      - key: SECURITY_JWT_SECRET
        value: "fake-jwt-secret"
