services:
  - type: web
    name: spring-boot-app          # довільне ім'я сервісу
    runtime: docker
    region: Oregon (US West)              # виберіть регіон (наприклад, EU – Frankfurt)
    plan: free                     # план (Starter Free)
    healthCheckPath: /            # шлях для перевірки стану (за потреби)
    envVars:
      - key: PORT
        value: "10000"
      # --- Змінні для OAuth2/JWT (приклад)
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
        value: fake-client-id
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
        value: fake-secret
      - key: JWT_SECRET
        value: fake-jwt-secret
